name: LiveFleaPrice Fetcher

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run fetch

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'prices.json tarkovdevprices.json'
          message: 'Update prices'

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_by_state_pattern: deleted, disabled_fork, disabled_inactivity, disabled_manually

                
